# Generated by Django 6.0.4 on 2026-05-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='court_images/'),
        ),
    ]
